version: '3'

services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - aroundtheblock-node_modules:/workspace/frontend/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  aroundtheblock-node_modules:
