"""Sample Post models to use in the development environment.

These were intially designed to be used by the `script.reset_db` module."""

from ...models import Post
from datetime import datetime

models = []

models.append(Post(id=1,
            img="https://cdnb.artstation.com/p/assets/images/images/024/888/131/large/seunghee-lee-9-final22s1000.jpg?1583861930",
            title="Swordwoman 1",
            desc="Art by https://www.artstation.com/seunghee",
            private=False,
            created=datetime.now(),
            challenge=2,
            user_id="lucy@lucy.com",
            comments=[],
            tags=["weChallenge"]))

models.append(Post(id=2,
            img="https://cdnb.artstation.com/p/assets/images/images/005/530/553/large/hicham-habchi-katana-girl.jpg?1491746594",
            title="Swordwoman 2",
            desc="Art by https://www.artstation.com/hichamhabchi1",
            private=False,
            created=datetime.now(),
            challenge=2,
            user_id="lucy@lucy.com",
            comments=[],
            tags=["weChallenge"]))

models.append(Post(id=3,
            img="",
            desc="Privacy test",
            private=True,
            created=datetime.now(),
            challenge=1,
            user_id="anonymous",
            comments=[],
            tags=["weChallenge"]))

models.append(Post(id=4,
               img="https://i.imgur.com/zNt5J1a.png",
               title="this is fine",
               desc="help",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="elaine13@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=5,
               img="https://i.imgur.com/yBMD0lE.png",
               title="a call for help",
               desc=":)",
               private=False,
               created=datetime.now(),
               challenge=11,
               user_id="elaine13@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=6,
               img="https://i.etsystatic.com/isla/053d60/42235724/isla_fullxfull.42235724_i9t43kmy.jpg?version=0",
               title="Bubblegum",
               desc="Source: https://www.etsy.com/shop/byMorganRoth",
               private=False,
               created=datetime.now(),
               challenge=2,
               user_id="lucy@lucy.com",
               comments=[],
               tags=["weChallenge"]))

models.append(Post(id=7,
               img="https://cdna.artstation.com/p/assets/images/images/053/302/294/large/royalskies-moonswing.jpg?1661891003",
               title="Construction",
               desc="AI art generated by https://www.artstation.com/royalskies",
               private=False,
               created=datetime.now(),
               challenge=9,
               user_id="olivia@olivia.com",
               comments=[],
               tags=["urban", "meChallenge"]))

models.append(Post(id=8,
               img="https://cdnb.artstation.com/p/assets/images/images/053/302/305/large/royalskies-adventurewithfriends.jpg?1661891015",
               title="Man's Best Friend",
               desc="AI art generated by https://www.artstation.com/royalskies",
               private=False,
               created=datetime.now(),
               challenge=9,
               user_id="olivia@olivia.com",
               comments=[],
               tags=["nature", "meChallenge"]))

models.append(Post(id=9,
               img="https://cdnb.artstation.com/p/assets/images/images/053/302/365/large/royalskies-thelake.jpg?1661891102",
               title="Lonely Nights",
               desc="AI art generated by https://www.artstation.com/royalskies",
               private=True,
               created=datetime.now(),
               challenge=9,
               user_id="olivia@olivia.com",
               comments=[],
               tags=["meChallenge"]))

models.append(Post(id=10,
               img="https://devhumor.com/content/uploads/images/March2022/new_bugs.jpg",
               title="me @ y'all",
               desc="demo day be like",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=11,
               img="https://i.pinimg.com/originals/34/fe/4b/34fe4b73e0a488f482c46b5388469861.png",
               title="me n elaine b like",
               desc="lol",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=12,
               img="https://i.imgur.com/Opwuckr.png",
               title="elaine calling me out",
               desc="sorry <3",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=13,
               img="https://i.imgur.com/iAtjzlC.png",
               title="lol",
               desc="i am just shitposting highlights from the dev team atp",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=14,
               img="https://res.cloudinary.com/practicaldev/image/fetch/s--DDDvUQUe--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/741b87500f9eip1evmj2.jpg",
               title="css",
               desc="appreciation post for elaine",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=15,
               img="https://user-images.githubusercontent.com/8677283/27186368-0b5bbdde-51e0-11e7-8d7b-e171a006600e.png",
               title="pytest",
               desc="us when we couldn't get pytests to work....",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=16,
               img="https://i.imgur.com/JCbqWhy.png",
               title="it's true",
               desc="please save me from comp 550",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=17,
               img="https://i.imgur.com/KNWP5a0.png",
               title="imgur",
               desc="the exact moment i realiized...",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=18,
               img="https://www.meme-arsenal.com/memes/0f6081de7e99b07b29e2c569a16ed470.jpg",
               title="bruh",
               desc="me when elaine breaks my code",
               private=False,
               created=datetime.now(),
               challenge=10,
               user_id="keaw@email.unc.edu",
               comments=[],
               tags=["meme"]))

models.append(Post(id=19,
               img="https://cdna.artstation.com/p/assets/images/images/055/128/704/large/sylvain-sarrailh-cypress-cliff.jpg?1666189543",
               title="The Cypress Cliff",
               desc="Source: https://www.artstation.com/artwork/QnQWkd",
               private=False,
               created=datetime.now(),
               challenge=5,
               user_id="lucy@lucy.com",
               comments=[],
               tags=["weChallenge", "Digital 2D"]))

models.append(Post(id=20,
               img="https://cdna.artstation.com/p/assets/images/images/012/025/022/large/claud-z-date.jpg?1532624146",
               title="Date",
               desc="Source: https://www.artstation.com/artwork/3Kk0v",
               private=False,
               created=datetime.now(),
               challenge=3,
               user_id="lucy@lucy.com",
               comments=[],
               tags=["weChallenge", "Digital 2D"]))

models.append(Post(id=21,
               img="https://cdna.artstation.com/p/assets/images/images/037/378/224/large/ismail-inceoglu-on-fire.jpg?1620224247",
               title="On Fire",
               desc="Source: https://www.artstation.com/artwork/18D5XG",
               private=False,
               created=datetime.now(),
               challenge=3,
               user_id="lucy@lucy.com",
               comments=[],
               tags=["weChallenge", "Concept Art"]))

models.append(Post(id=22,
              img="https://cdn.discordapp.com/attachments/525419273888202795/1098122459997282394/IMG_3058.jpg",
              title="Dreamy Mountains",
              desc="<3",
              private=False,
              created=datetime.now(),
              challenge=6,
              user_id="elaine13@email.unc.edu",
              comments=[],
              tags=["landscape", "impressionism", "meChallenge"]))

models.append(Post(id=23,
               img="https://cdn.discordapp.com/attachments/525419273888202795/1098263927130959882/IMG_2954.jpg",
               title="Venice on Fire",
               desc="Made with acrylics, inspired by Leonid Afremov.",
               private=False,
               created=datetime.now(),
               challenge=7,
               user_id="elaine13@email.unc.edu",
               comments=[],
               tags=["impressionism", "meChallenge"]))

models.append(Post(id=24,
               img="https://cdn.discordapp.com/attachments/525419273888202795/1098288726834167838/IMG_3054.jpg",
               title="Love Birds",
               desc="Just two birds on a powerline.",
               private=False,
               created=datetime.now(),
               challenge=8,
               user_id="elaine13@email.unc.edu",
               comments=[],
               tags=["urban", "meChallenge"]))